version: "3.3"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
  app:
    depends_on:
      - mongodb
    image: backend:latest
    restart: on-failure
    ports:
      - 8079:8079
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.uri" : "mongodb://mongodb:27017/HappyFaces",
      }'
